services:
  - type: web
    name: my-nest-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: NODE_OPTIONS="--max-old-space-size=512" npm run start:prod
    envVars:
      - key: DATABASE_URL
        sync: false
